"""setup script 
"""
import os.path as osp
from setuptools import setup, find_packages

_NAME = "unremarkable"

def _path(*args):
    return osp.join(osp.split(__file__)[0], *args)

def _set_version(version):
    with open(_path(_NAME,'version.py'), 'w', encoding='utf8') as _fi:
        _fi.write('"""@xvdp generated by setup.py"""\n')
        _fi.write("__version__='"+version+"'\n")
    return version

def _requirements():
    with open(_path('requirements.txt'), encoding='utf8') as _fi:
        return _fi.read().split()

setup(
    name=_NAME,
    version=_set_version("0.0.3"),
    packages=find_packages(),
    install_requires=_requirements(),
    entry_points={
        'console_scripts': [
            'pdf_info=unremarkable.__main__:pdf_info',  # . local pdf info: num pages, width, height
            'pdf_to_remarkable=unremarkable.__main__:pdf_to_remarkable',    # -> upload pdf
            'remarkable_backup=unremarkable.__main__:remarkable_backup',    # <- backup to local
            'remarkable_ls=unremarkable.__main__:remarkable_ls', # . list files on backup
            'remarkable_export_annotated=unremarkable.__main__:remarkable_export_annotated',
            'remarkable_read_rm=unremarkable.__main__:remarkable_read_rm',
            'remarkable_help=unremarkable.__main__:remarkable_help'

        ],
    },
    python_requires='>=3.6',
    tests_require=["pytest"]
)
