"""setup script 
"""
import os.path as osp
from setuptools import setup, find_packages

_NAME = "unremarkable"

def _path(*args):
    return osp.join(osp.split(__file__)[0], *args)

def _set_version(version):
    with open(_path(_NAME,'version.py'), 'w', encoding='utf8') as _fi:
        _fi.write('"""@xvdp generated by setup.py"""\n')
        _fi.write("__version__='"+version+"'\n")
    return version

def _requirements():
    with open(_path('requirements.txt'), encoding='utf8') as _fi:
        return _fi.read().split()

setup(
    name=_NAME,
    version=_set_version("0.0.1"),
    packages=find_packages(),
    install_requires=_requirements(),
    entry_points={
        'console_scripts': [
            'pdf_to_remarkable=unremarkable.unremarkable:pdf_to_remarkable_fun',
            'backup_remarkable=unremarkable.unremarkable:backup_remarkable_fun'
        ],
    },
    python_requires='>=3.6',
    tests_require=["pytest"]
)
