"""setup script 
"""
import os.path as osp
from setuptools import setup, find_packages

_NAME = "unremarkable"

def _path(*args):
    return osp.join(osp.split(__file__)[0], *args)

def _set_version(version):
    with open(_path(_NAME,'version.py'), 'w', encoding='utf8') as _fi:
        _fi.write('"""@xvdp generated by setup.py"""\n')
        _fi.write("__version__='"+version+"'\n")
    return version

def _requirements():
    with open(_path('requirements.txt'), encoding='utf8') as _fi:
        return _fi.read().split()

setup(
    name=_NAME,
    version=_set_version("0.0.2"),
    packages=find_packages(),
    install_requires=_requirements(),
    entry_points={
        'console_scripts': [
            'pdf_info=unremarkable.unremarkable:pdf_info',  # . local pdf info: num pages, width, height
            'pdf_to_remarkable=unremarkable.unremarkable:pdf_to_remarkable',    # -> upload pdf to remarkable
            'remarkable_backup=unremarkable.unremarkable:remarkable_backup',    # <- backup to local
            'remarkable_file_graph=unremarkable.unremarkable:remarkable_file_graph', # deprecate
            'remarkable_ls=unremarkable.unremarkable:remarkable_file_graph', # . list files on backup
            'remarkable_export_annotated=unremarkable.unremarkable:remarkable_export_annotated', # . wip scales are wrong
            # 'remarkable_export_rm=unremarkable.unremarkable:remarkable_export_rm', # . wip s

        ],
    },
    python_requires='>=3.6',
    tests_require=["pytest"]
)
